version: "3.7"

services:
  celery-worker:
    volumes:
      - .:/app

  celery-beat:
    volumes:
      - .:/app

  django:
    command: ["pytest"]   # 通过 pycharm 运行的也是 runserver 命令
    volumes:
      - .:/app