version: "3.7"

services:
  celery-worker:
    command: /usr/local/bin/celery worker --app=pytest_backend --loglevel=DEBUG
    volumes:
      - .:/app

  celery-beat:
    command: /usr/local/bin/celery beat --app=pytest_backend --loglevel=DEBUG
    volumes:
      - .:/app

  django:
    command: ["pytest"]   # 通过 pycharm 运行的也是 runserver 命令
    volumes:
      - .:/app