# Generated by Django 2.1.7 on 2019-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
